export const CLUSTERS_POR_HUB = {  
  "LM Hub_SP_Itaqua_Zimba": [  
    "Vila São Paulo",  
    "Parque São Pedro",  
    "Cidade Tiradentes",  
    "Parque Lucélia",  
    "Vila Roseira II",  
    "Parque Santa Tereza",  
    "Jardim Marpu",  
    "Parque Res. Marengo",  
    "Jardim São joão",  
    "Jardim Irene",  
    "Una",  
    "Lageado",  
    "Arujazinho",  
    "Parque Viviane",  
    "Itaquaquecetuba",  
    "Aruã",  
    "Vila Pilar",  
    "Amazonas / Taboão",  
    "Jardim Guaracy",  
    "Jardim Caiubi",  
    "Jardim dos Pereiras",  
    "Jardim Alice",  
    "Centro Industrial",  
    "Pouso Alegre",  
    "Mirante do Arujá",  
    "Estância São José",  
    "Jardim das Oliveiras - z",  
    "Jardim Guaracy - z",  
    "Jardim dos Pereiras - z",  
    "Cidade Tiradentes - z",  
    "Jardim Alice - z",  
    "Amazonas_Taboão - z",  
    "Itaquaquecetuba - Vila Gepina",  
    "Itaquaquecetuba - Vila Londrina",  
    "Itaquaquecetuba -  Pedreira",  
    "Itaquaquecetuba - Vila São João"  
  ],  
  "LM Hub_SP_Guarulhos": [  
    "03. Jardim Robru",  
    "01. Itaim Paulista",  
    "16. Aeroporto",  
    "14. Fortaleza",  
    "09. São Miguel",  
    "10. Cumbica",  
    "06. Itaquaquecetuba",  
    "15. Jardim Pres. Dutra",  
    "13. Bonsucesso",  
    "08. Dom Miguel",  
    "05. Jardim Nélia",  
    "11. Parque Jurema",  
    "04. Jardim Luciana",  
    "02. Jardim São Vicente",  
    "07. Vanderlei do Prado",  
    "12. Água Chata",  
    "Bonsucesso - z",  
    "Fortaleza",  
    "Jardim Robru",  
    "Dom Miguel",  
    "Cumbica",  
    "Parque Jurema",  
    "São Miguel",  
    "Jardim Pres. Dutra",  
    "Jardim Luciana",  
    "Jardim Nélia - z",  
    "Itaim Paulista",  
    "Água Chata",  
    "Jardim São Vicente - z",  
    "Itaquaquecetuba - z",  
    "Aeroporto",  
    "Vanderlei do Prado - z",  
    "G-6",  
    "A-4",  
    "B-4",  
    "E-4",  
    "E-13",  
    "F-13",  
    "B-8",  
    "F-2",  
    "F-9",  
    "C-11",  
    "B-13",  
    "F-7",  
    "C-14",  
    "C-12",  
    "B-14",  
    "H-6",  
    "B-3",  
    "G-9",  
    "A-1",  
    "F-5",  
    "G-11",  
    "H-7",  
    "A-12",  
    "A-3",  
    "B-5",  
    "G-14",  
    "G-4",  
    "H-2",  
    "F-14",  
    "H-5",  
    "G-5",  
    "C-13",  
    "D-1",  
    "D-5",  
    "G-13",  
    "H-4",  
    "C-7",  
    "B-9",  
    "C-3",  
    "G-10",  
    "B-2",  
    "A-2",  
    "D-7",  
    "B-6",  
    "D-10",  
    "D-6",  
    "D-14",  
    "B-10",  
    "A-8",  
    "C-4",  
    "B-11",  
    "H-3",  
    "G-12",  
    "C-5",  
    "B-1",  
    "G-3",  
    "D-12",  
    "B-7",  
    "F-4",  
    "C-9",  
    "C-1",  
    "G-7",  
    "A-14",  
    "A-5",  
    "D-8",  
    "H-12",  
    "F-3",  
    "B-12",  
    "A-7",  
    "F-8",  
    "F-12",  
    "F-11",  
    "H-1",  
    "H-8",  
    "C-8",  
    "D-3",  
    "E-6",  
    "A-9",  
    "C-2",  
    "F-10",  
    "D-9",  
    "E-11",  
    "C-6",  
    "D-13",  
    "E-2",  
    "D-4",  
    "G-2",  
    "E-10",  
    "C-10",  
    "H-10",  
    "E-14",  
    "E-3"  
  ],  
  "LM Hub_SP_Parque Novo Mundo": [  
    "12. Vila Matilde",  
    "17. Guarulhos",  
    "16. Cangaiba",  
    "19. Vila Galvão",  
    "14. Tatuapé",  
    "13. Vila Esperança",  
    "20. Parque Novo Mundo",  
    "10. Vila Carrão",  
    "06. Luiz Fagundes",  
    "11. Vila Gomes Cardim",  
    "18. Ponte Grande",  
    "15. Cidade de Deus",  
    "01. Terra Preta",  
    "09. Vila Formosa",  
    "03. Mato Dentro",  
    "08. Boa Vista",  
    "02. Vila Pedra Vermelha",  
    "07. Serra da Cantareira",  
    "Parque Novo Mundo",  
    "Tatuapé",  
    "Guarulhos",  
    "Vila Matilde",  
    "Vila Galvão",  
    "Vila Maria",  
    "Vila Gomes Cardim",  
    "Cidade de Deus",  
    "Cangaiba",  
    "Vila Carrão",  
    "Ponte Grande",  
    "Vila Esperança",  
    "Caceia - z",  
    "Pedra Vermelha - z",  
    "Terra Preta  - z",  
    "Mato Dentro - z",  
    "Jardim Marisol - z",  
    "Vila Formosa",  
    "Serra da Cantareira - z",  
    "Luiz Fagundes  - z",  
    "Centro - z",  
    "Boa Vista - z",  
    "Vila Machado - z",  
    "Rio Acima  - z",  
    "Parque Boturussu",  
    "Terra Preta - z",  
    "Luiz Fagundes - z"  
  ],  
  "LM Hub_SP_Embu das Artes": [  
    "Roselândia",  
    "Parque Esplanada",  
    "Embu das Artes",  
    "Cotia",  
    "Jardim Samambaia",  
    "Rio Cotia",  
    "São Lourenço",  
    "Vila do Sol",  
    "Recreio Primavera",  
    "Cidade Ipava",  
    "Jardim dos Moraes",  
    "Cipó Guaçu",  
    "Brotas",  
    "Juquitiba",  
    "Embu Guaçu",  
    "Lagoa",  
    "Jardim Valflor",  
    "Embu Mirim",  
    "Jardim Vale Verde",  
    "Granja Viana",  
    "Itapecerica da Serra",  
    "Jardim Petropolis",  
    "Refúgio da Serra",  
    "Jardim Santa Lúcia",  
    "Jardim das Oliveiras",  
    "Parque Imperial",  
    "Loteamento Chácaras",  
    "Jardim Vale Verde - z",  
    "Vila do Sol - z",  
    "Cidade Ipava - z",  
    "Jardim Samambaia - z"  
  ],  
  "LM Hub_SP_Itapevi": [  
    "14. ITAPEVI - COTIA",  
    "10. JANDIRA",  
    "04. SANTANA PARNAIBA",  
    "16. ITAPEVI",  
    "12. ITAPEVI",  
    "03. VARGEM GRANDE",  
    "15. ITAPEVI",  
    "11. JANDIRA",  
    "13. ITAPEVI",  
    "07. SÃO ROQUE",  
    "02. PIRAPORA",  
    "05. SANTANA PARNAIBA",  
    "09. COTIA"  
  ],  
  "LM Hub_SP_Osasco_02": [  
    "06. Osasco KM 18",  
    "04. Carapicuíba Vila Dirce",  
    "05. Carapicuíba",  
    "03. Osasco Centro",  
    "02. Jaguaré",  
    "01. Rio Pequeno",  
    "09. Butantã",  
    "08. Vila Menck",  
    "Osasco KM 18 - 01 - z",  
    "Carapicuíba Vila Dirce - z",  
    "Vila Menck",  
    "Carapicuíba - z",  
    "Osasco Centro",  
    "Jaguaré - z",  
    "Osasco KM 18 - 02",  
    "Butantã"  
  ],  
  "LM Hub_SP_Barueri_01": [  
    "05. Vila Menck",  
    "07. Santana de Parnaíba",  
    "06. Parque Viana",  
    "01. Alphaville",  
    "16. Perus",  
    "03. Rochdale",  
    "14. Jardim Santa Fé",  
    "08. Chácara São Pedro",  
    "10. Chácara do Solar",  
    "04. Portal do Oeste",  
    "13. Jandira",  
    "02. Tamboré",  
    "09. Sítio do Rosário",  
    "12. Barueri",  
    "11. Chácara Marco",  
    "15. Chácara Sol Nascente",  
    "Barueri",  
    "Rochdale - 01",  
    "Chácara São Pedro",  
    "Jardim Santa Fé - z",  
    "Jandira",  
    "Portal do Oeste - z",  
    "Santana de Parnaíba",  
    "Parque Viana",  
    "Tamboré",  
    "Chácara Marco",  
    "Vila Menck - 01 - z",  
    "Rochdale - 02",  
    "Alphaville - 02",  
    "Sítio do Rosário",  
    "Vila Menck - 02",  
    "Perus - z",  
    "Chácara do Solar",  
    "Chácara Sol Nascente",  
    "Alphaville - 01 - z",  
    "São Domingos"  
  ],  
  "LM Hub_SP_Embu das Artes_02": [  
    "07. Jardim Arpoador",  
    "06. Jardim Celeste",  
    "08. Taboão da Serra",  
    "11. Valo Velho",  
    "09. Jardim Record",  
    "03. Rio Pequeno",  
    "10. Jardim São Bento",  
    "02. Vila Sonia",  
    "05. Morumbizinho",  
    "12. Jardim dos Moraes",  
    "14. Jardim Castilho",  
    "04. Jardim Jaqueline",  
    "01. City Butatã",  
    "Jardim Arpoador",  
    "Jardim Castilho",  
    "Rio Pequeno - z",  
    "Taboão da Serra",  
    "Valo Velho - z",  
    "Jardim São Bento - z",  
    "Jardim Record",  
    "Jardim dos Moraes - z",  
    "City Butatã",  
    "Jardim Jaqueline",  
    "Morumbizinho",  
    "Jardim Celeste"  
  ],  
  "LM Hub_SP_São Paulo_Mooca": [  
    "Sacomã, Vila Água Funda",  
    "Vila da Saúde",  
    "Vila Prudente",  
    "Vila Formosa, Carrão",  
    "Vila Carioca",  
    "Ipiranga",  
    "Alpina",  
    "São Caetano do Sul",  
    "Heliópolis",  
    "Climaco",  
    "Mooca",  
    "Vila Mariana",  
    "Moema",  
    "Bosque da Saúde",  
    "Sacomã",  
    "Vila Carioca 2",  
    "Vila Agua Funda",  
    "Climaco - z",  
    "Heliópolis - z",  
    "Sacomã - z",  
    "Vila Carioca 2 - z",  
    "Vila Agua Funda - z"  
  ],  
  "LM Hub_SP_São Paulo_Lapa": [  
    "Marilândia - z",  
    "Parque Taipas - z",  
    "Pinheiros - 02 - z",  
    "Jardim Paulistano - z",  
    "Vila Penteado - 02 - z",  
    "Pirituba - z",  
    "Jardim Vista Alegre - z",  
    "Vila Romana",  
    "Freguesia do Ó - z",  
    "Brasilândia - z",  
    "Perdizes - 01",  
    "Vila Jaguara",  
    "Lapa - 01",  
    "Lapa - 02 - z",  
    "Piqueri - z",  
    "Jardim Rincão - z",  
    "Cidade Patricarca",  
    "Vila Yara - z",  
    "Jaraguá - z",  
    "Vila Siqueira"  
  ],  
  "LM Hub_SP_São Paulo_Carandiru": [  
    "Brás - z",  
    "Furas",  
    "Mandaqui",  
    "Vila Mazzei",  
    "Tucuruvi",  
    "Belenzinho",  
    "Jardim Peri - 01 - z",  
    "Recanto Verde - 01",  
    "Vila Guilherme",  
    "Jardim Peri - 02",  
    "Cachoeirinha",  
    "Recanto Verde - 02",  
    "Vila Medeiros",  
    "Vila Mazzei_02",  
    "Jardim Peri_02",  
    "Jardim Peri_01 - z",  
    "Recanto Verde_01",  
    "Recanto Verde_02",  
    "Vila Mazzei_01"  
  ],  
  "LM Hub_SP_Mooca_02": [  
    "08. Cambuci",  
    "02. Vila Formosa",  
    "06. Paraíso",  
    "01. Mooca",  
    "07. Regente Feijó",  
    "04. Ipiranga",  
    "03. Saúde",  
    "05. Moema",  
    "Cambuci",  
    "Regente Feijó",  
    "Paraíso"  
  ],  
  "LM Hub_SP_VilaGuilherme": [  
    "Bom Retiro",  
    "Vila Guilherme_Vila Maria",  
    "Bela Vista - 01",  
    "Jardim Japão",  
    "Jardim Primavera",  
    "Consolação_9 de Julho - 01",  
    "Santa Cecilia_Vila Buarque",  
    "Vila Guilherme_Santana",  
    "Casa Verde_Limão",  
    "Pacaembu_Sumaré",  
    "Luz_República",  
    "Barra Funda",  
    "Jardim Brasil",  
    "Jardim Paulista",  
    "Consolação 9 de Julho - 02 - z",  
    "Jardins_Itaim Bibi",  
    "Canindé - z",  
    "Praça João Mendes - 02 - z",  
    "Casa Verde_Jardim São Bento",  
    "Praça João Mendes - 01",  
    "Jardim Paulistano",  
    "Liberdade - 02 - z",  
    "Liberdade - 01",  
    "Bela Vista - 02 - z",  
    "Pacaembu",  
    "Luz_República_02",  
    "Luz_República_01",  
    "Sumaré",  
    "Vila Constança",  
    "Jardim Paulista - z",  
    "Canindé",  
    "Liberdade - 02",  
    "Jardins_Itaim Bibi - z",  
    "Bela Vista - 02",  
    "Consolação 9 de Julho - 02",  
    "Praça João Mendes - 02",  
    "Freguesia do Ó"  
  ],  
  "LM Hub_SP_Campinas_PqCidade": [  
    "21_Cluster_21",  
    "07_Cluster_7",  
    "02_Cluster_2",  
    "19_Cluster_19",  
    "13_Cluster_13",  
    "12_Cluster_12",  
    "05_Cluster_5",  
    "11_Cluster_11",  
    "14_Cluster_14",  
    "18_Cluster_18",  
    "17_Cluster_17",  
    "15_Cluster_15",  
    "20_Cluster_20",  
    "03_Cluster_3",  
    "16_Cluster_16",  
    "06_Cluster_6",  
    "10_Cluster_10",  
    "Jardim Leonor",  
    "Jardim Novo Flamboyant",  
    "Jardim Chapadão",  
    "Centro Campinas - z",  
    "Centro Indaiatuba",  
    "Satélite Íris",  
    "Morada do Sol",  
    "Taquaral",  
    "Jardim Santa Mônica",  
    "Lot Alphaville Campinas",  
    "Conj Hab Parque Itajaí",  
    "Jardim Ouro Verde",  
    "Cambuí",  
    "Francisco Quirino",  
    "Helvétia Park",  
    "Parque Ecológico",  
    "Recanto dos Dourados - z",  
    "Cidade Universitária",  
    "Village Campinas - z",  
    "Jardim Itatinga"  
  ],  
  "LM Hub_SP_Limeira_Campo Belo": [  
    "04_Cluster_4",  
    "01_Cluster_1",  
    "10_Cluster_11"  
  ],  
  "LM Hub_SP_Mogi Mirim": [  
    "Mogi Mirim",  
    "Engenheiro Coelho",  
    "Santo Antônio de Posse",  
    "Serra Negra",  
    "Mogi Guaçu",  
    "Artur Nogueira",  
    "Itapira",  
    "Pedreira",  
    "Lindóia",  
    "Jaguariúna",  
    "Socorro",  
    "Águas de Lindóia",  
    "Holambra - z",  
    "Estiva Gerbi"  
  ],  
  "LM Hub_SP_Leme": [  
    "Araras",  
    "Pirassununga",  
    "Porto Ferreira",  
    "Leme",  
    "Conchal",  
    "Cachoeira de Emas"  
  ],  
  "LM Hub_SP_Piracicaba": [  
    "10. Piracicamirim",  
    "03. Capivari",  
    "08. Vila Rezende",  
    "07. Rio das Pedras",  
    "05. Santa Bárbara d'Oeste",  
    "04. Bom Retiro",  
    "09. Água Bonita",  
    "01. Charqueada",  
    "11. Piracicaba_Centro",  
    "02. Águas de São Pedro",  
    "02. São Pedro",  
    "Piracicamirim",  
    "Centro",  
    "SBO 2",  
    "Mario Dedini",  
    "Rio das Pedras",  
    "Capivari",  
    "Aguas de São Pedro",  
    "Artemis",  
    "Campestre",  
    "São Pedro",  
    "Santana",  
    "SBO 1",  
    "Jupia",  
    "Charqueada",  
    "Santa Rosa",  
    "SBO 3",  
    "São Jorge"  
  ],  
  "LM Hub_SP_Sumaré_Nova Veneza": [  
    "06. Campinas I",  
    "22. Sumaré V",  
    "19. Sumaré II",  
    "12. Paulínia III",  
    "15. Hortolândia III",  
    "18. Sumaré I",  
    "05. Nova Odessa II",  
    "21. Sumaré IV",  
    "09. Campinas IV",  
    "11. Paulínia II",  
    "17. Hortolândia V",  
    "03. Monte Mor II",  
    "23. Sumaré VI",  
    "10. Paulínia I",  
    "13. Hortolândia I",  
    "07. Campinas II",  
    "08. Campinas III",  
    "20. Sumaré III",  
    "16. Hortolândia IV",  
    "14. Hortolândia II",  
    "01. Elias Fausto",  
    "04. Nova Odessa I",  
    "02. Monte Mor I",  
    "Campinas IV",  
    "Sumaré V",  
    "Sumaré IV",  
    "Paulínia II",  
    "Sumaré II",  
    "Monte Mor II",  
    "Hortolândia V",  
    "Sumaré VI",  
    "Nova Odessa",  
    "Sumaré I",  
    "Paulínia III",  
    "Campinas III",  
    "Hortolândia III",  
    "Hortolândia I",  
    "Campinas I",  
    "Paulínia I",  
    "Hortolândia IV",  
    "Monte Mor I",  
    "Sumaré III",  
    "Elias Fausto",  
    "Campinas II",  
    "Hortolândia II"  
  ],  
  "LM Hub_SP_Jundiaí": [  
    "Parque Santa Isabel",  
    "Jardim Bertioga",  
    "Bairro do Mina",  
    "Parque Eloy Chaves",  
    "Gramadão",  
    "Jardim América",  
    "Jardim Italia",  
    "São Camilo",  
    "Cecap",  
    "Fazenda Grande",  
    "Cafezal",  
    "Anhangabaú",  
    "Paiol Velho",  
    "Vila Cidadania",  
    "Louveira",  
    "Almerinda Chaves",  
    "Jardim Santa Gertrudes",  
    "Itu Centro",  
    "Parque do Lago",  
    "Jundiaí Centro",  
    "Jacaré",  
    "Corrupira",  
    "Chácara Flórida",  
    "Rio Acima",  
    "Cabreúva",  
    "Cidade Nova",  
    "Caxambu",  
    "Medeiros",  
    "Monte Serrat",  
    "Porto Góis",  
    "Bom Fim do Bom Jesus",  
    "Cachambu",  
    "Roseira",  
    "Barão da Boa Vista",  
    "Ivoturucaia",  
    "Fazenda Campo Verde",  
    "Jardim Italia - z",  
    "Jardim Bertioga - z",  
    "Jardim América - z",  
    "São Camilo - z",  
    "Itu Centro - z",  
    "Chácara Flórida - z",  
    "Cidade Nova - z",  
    "Parque do Lago - z",  
    "Caxambu - z",  
    "Terras de Jundiaí - z",  
    "Fazenda Velha"  
  ],  
  "LM Hub_SP_Campinas_São Martinho": [  
    "09_Cluster_9",  
    "22_Cluster_22",  
    "08_Cluster_8",  
    "24_Cluster_24",  
    "Valinhos",  
    "Sousas",  
    "Jardim Nova Europa",  
    "Vinhedo",  
    "Swiss Park",  
    "Jardim Campo Belo - z",  
    "Swift"  
  ],  
  "LM Hub_SP_Várzea Paulista": [  
    "14. Botujuru",  
    "16. Panorama",  
    "13. Jardim Vassouras",  
    "05. Serpa",  
    "22. Vila Verde",  
    "06. Estância Lago Azul",  
    "09. Vila Suiça",  
    "21. Vila Nova",  
    "20. Ponunduva",  
    "04. Parque Vitoria",  
    "02. Laranjeiras",  
    "07. Vila São Benedito",  
    "25. Vigoreli",  
    "08. Parque Montreal",  
    "10. Chácara São Luiz",  
    "03. Nova Caieiras",  
    "15. Paraíso",  
    "11. Vila Natal",  
    "12. Vila Cariri",  
    "01. Parque Suiça",  
    "23. Parque São Roberto",  
    "17. Polvinho",  
    "24. Vila das Américas",  
    "33. Tijuco Preto",  
    "19. Guaturinho",  
    "18. Portais",  
    "Panorama - z",  
    "Parque Montreal - z",  
    "Botujuru - z",  
    "Parque São Roberto - z",  
    "Vila Nova",  
    "Vila Suiça - z",  
    "Jardim Vassouras - z",  
    "Vila São Benedito - z",  
    "Parque Vitoria",  
    "Estância Lago Azul - z",  
    "Paraíso - z",  
    "Vila Natal - z",  
    "Polvinho - z",  
    "Nova Caieiras",  
    "Chácara São Luiz - z",  
    "Tijuco Preto - z",  
    "Vila Verde - z",  
    "Serpa",  
    "Vila das Américas",  
    "Portais - z",  
    "Guaturinho - z",  
    "Ponunduva - z",  
    "Vila Cariri - z",  
    "Parque Suiça - z",  
    "Vigoreli - z"  
  ],  
  "LM Hub_SP_Atibaia_Ponte_Alta": [  
    "Atibaia IV",  
    "Atibaia VI",  
    "Jarinu I",  
    "Campo Limpo Paulista III",  
    "Piracaia",  
    "Atibaia I",  
    "Campo Limpo Paulista II",  
    "Bragança Paulista III",  
    "Bragança Paulista II",  
    "Bragança Paulista V",  
    "Monte Alegre do Sul",  
    "Bragança Paulista I",  
    "Pinhalzinho",  
    "Bom Jesus dos Perdões",  
    "Atibaia V",  
    "Joanópolis",  
    "Bragança Paulista VI",  
    "Itatiba II",  
    "Morungaba",  
    "Bragança Paulista IV",  
    "Atibaia VII",  
    "Itatiba IV",  
    "Jarinu II",  
    "Atibaia III",  
    "Vargem",  
    "Amparo",  
    "Atibaia II",  
    "Pedra Bela",  
    "Campo Limpo Paulista I",  
    "Itatiba I",  
    "Nazaré Paulista",  
    "Tuiuti",  
    "Piracaia II",  
    "Piracaia I",  
    "Jarinu I - z",  
    "Campo Limpo Paulista III -z",  
    "Jarinu II - z",  
    "Arcadas",  
    "Campo Limpo Paulista II - z",  
    "Campo Limpo Paulista I - z",  
    "Vicente Nunes",  
    "Itatiba III"  
  ],  
  "LM Hub_SP_Sorocaba_Região Norte": [  
    "Aluminio",  
    "Alumínio",  
    "Araçariguama",  
    "Araçoiaba da Serra",  
    "Araçoiaba da Serra_1",  
    "Araçoiaba da Serra_2",  
    "Araçoiaba da Serra_3",  
    "Dona Catarina",  
    "Ibiuna 1 - z",  
    "Ibiuna 2 - z",  
    "Ibiuna 3 - z",  
    "Ibiuna 4 - z",  
    "Mairanque_1",  
    "Mairanque_2",  
    "Mairanque_3",  
    "Mairinque -  Dona Catarina",  
    "Mairinque - Centro",  
    "Mairinque - Porta do Sol",  
    "Mairinque_1",  
    "Mairinque_2",  
    "Mairinque_3",  
    "Piedade",  
    "Piedade, Paruru",  
    "Porta do Sol",  
    "Ressaca",  
    "Salto",  
    "Salto de Pirapora",  
    "Salto_1",  
    "Salto_2",  
    "Salto_3",  
    "Salto_4",  
    "Salto_5",  
    "Salto, Itu, Leste",  
    "São Roque - Canguera",  
    "São Roque - Centro",  
    "São Roque - Mailasqui",  
    "São Roque_Canguera",  
    "São Roque_Centro",  
    "Sorocaba - Brigadeiro",  
    "Sorocaba_10",  
    "Sorocaba, Aparecida",  
    "Sorocaba, Central Park",  
    "Sorocaba, Centro",  
    "Sorocaba, Éden",  
    "Sorocaba, Ibiti",  
    "Sorocaba, Ipanema",  
    "Sorocaba, Olga",  
    "Sorocaba, Prefeitura_2",  
    "Sorocaba, Santa Rosália",  
    "Sorocaba, São Bento",  
    "Sorocaba, Vitória",  
    "Sorocaba, Wanel Ville",  
    "Tapiraí, Rio Turvo",  
    "Votorantim 01",  
    "Votorantim 02",  
    "Votorantim 03",  
    "ZOF01 Ibiúna, Centro",  
    "ZOF02 Ibiúna, Centro",  
    "ZOF03 Ibiúna, Verava",  
    "ZOF04 Ibiúna, Lajeado"  
  ],  
  "LM Hub_SP_Itapeva": [  
    "Ribeirão Branco",  
    "Itapeva",  
    "Apiaí",  
    "Itaberá",  
    "Capão Bonito",  
    "Buri",  
    "Itaporanga",  
    "Itapirapuã Paulista_1",  
    "Itararé",  
    "Barra do Chapéu",  
    "Guapiara",  
    "Taquarivaí",  
    "Ribeira",  
    "Nova Campina",  
    "Bom Sucesso de Itararé",  
    "Ribeirão Branco - z",  
    "Itapirapuã Paulista - z",  
    "Taquarivaí - z",  
    "Apiaí - z"  
  ],  
  "LM Hub_SP_Registro": [  
    "Registro",  
    "Iha comprida - z",  
    "Cajati",  
    "Eldorado",  
    "Jacupiranga",  
    "Barra do Turvo - z",  
    "Iguape - z",  
    "Sete Barras",  
    "Miracatu",  
    "Pariquera Açu",  
    "Ariri Cananeia - z",  
    "Juquiá"  
  ],  
  "LM Hub_SP_Tatuí": [  
    "10. Tatuí",  
    "16. Capela do Alto",  
    "02. Laranjal Paulista",  
    "03. Tietê",  
    "01. Conchas",  
    "17. Boituva",  
    "06. Torre de Pedra",  
    "14. Porto Feliz_2",  
    "07. Porangaba",  
    "12. Cesário Lange",  
    "08. Cerquilho",  
    "05. Pereiras",  
    "13. Iperó",  
    "11. Quadra",  
    "15. Porto Feliz_Area Rural",  
    "09. Guarei",  
    "Tietê",  
    "Boituva",  
    "Laranjal Paulista",  
    "Cerquilho",  
    "Iperó",  
    "Porto Feliz_Area Rural",  
    "Conchas",  
    "Tatuí",  
    "Porto Feliz_2",  
    "Cesário Lange",  
    "Porangaba",  
    "Quadra",  
    "Capela do Alto",  
    "Pereiras",  
    "Jumirim"  
  ],  
  "LM Hub_SP_Itapetininga": [  
    "01. Angatuba",  
    "06. São Miguel Arcanjo",  
    "08. Alambari",  
    "14. Piedade",  
    "09. Itapetininga",  
    "10. Pilar do Sul",  
    "13. Salto de Pirapora",  
    "04. Tupy Rechan",  
    "02. Campina do Monte Alegre",  
    "07. Sarapuí",  
    "15. Tapiraí, Rio Turvo",  
    "05. Gramadinho",  
    "03. Guareí"  
  ],  
  "LM Hub_SP_Botucatu": [  
    "07. São Manuel",  
    "14. Jardim Brasil",  
    "13. Vila Di Capri",  
    "16. Botucatu",  
    "15. Jardim Maria Luiza",  
    "06. Areiópolis",  
    "11. Itatinga",  
    "05. Santa Maria da Serra",  
    "10. Pardinho_2",  
    "12. Anhembi",  
    "08. Pratânia_1",  
    "09. Bofete",  
    "10. Pardinho_1"  
  ],  
  "LM Hub_SP_São José dos Campos": [  
    "10. Sudeste - Flamboyant",  
    "07. Centro de SJC- Aquários- Ind",  
    "19. Zona Sul - Satélite",  
    "08. Centro de Jacareí",  
    "17. Zona Sul - Interlagos",  
    "18. Zona Sul - Vila Branca",  
    "14. Zona Leste - Jardim Majestic",  
    "09. Zona Oeste- Jd. das Indústri",  
    "21. Brandeira Branca",  
    "16. Cidade Salvador",  
    "13. Zona Norte - Buquirinha",  
    "11. Zona Norte- Altos de Santana",  
    "15. Zona Leste - Eugênio de Melo",  
    "20. Jacareí - Imperial",  
    "12. Zona Oeste- Urbanova- Meia L",  
    "06. São Francisco Xavier",  
    "05. Santa Branca",  
    "04. Jambeiro",  
    "03. Igaratá",  
    "01. Paraibuna",  
    "02. Monteiro Lobato",  
    "Zona Sul - Satélite",  
    "Aquarios",  
    "Brandeira Branca",  
    "Zona Sul - Interlagos",  
    "Parque Itamarati",  
    "Zona Norte - Buquirinha",  
    "Zona Leste - Jardim Majestic",  
    "Zona Sul - Vila Branca",  
    "Jacareí - Imperial",  
    "São Francisco Xavier",  
    "Zona Oeste - Jd. das Indústrias",  
    "Urbanova",  
    "Sudeste - Flamboyant",  
    "Zona Norte - Altos de Santana",  
    "Cidade Salvador",  
    "Zona Leste - Eugênio de Melo",  
    "Parque Meia Lua",  
    "Igaratá",  
    "Santa Branca",  
    "Paraibuna",  
    "Jambeiro"  
  ],  
  "LM Hub_SP_Artur Alvim": [  
    "06. Jardim Limoeiro",  
    "03. Parque Boturussu",  
    "08. Vila Carmosina",  
    "11. Vila Ré",  
    "09. Jardim Cibele",  
    "04. Campanela",  
    "07. Vila Brasil",  
    "13. Cidade Patriarca",  
    "05. Savoy",  
    "10. Vila Formosa",  
    "01. Iguatemi",  
    "14. São Mateus",  
    "12. Cidade Nova São Miguel",  
    "02. União Vila Nova",  
    "Campanela",  
    "Parque Boturussu - z",  
    "Savoy",  
    "Iguatemi - z",  
    "Vila Carmosina",  
    "Cidade Patriarca",  
    "Vila Ré",  
    "Jardim Cibele",  
    "Vila Brasil",  
    "São Mateus",  
    "Cidade Nova São Miguel",  
    "Jardim Limoeiro",  
    "União Vila Nova - z"  
  ],  
  "LM Hub_SP_Taubaté": [  
    "Tremembé",  
    "Taubaté - 01",  
    "Taubaté - 02",  
    "Taubaté - 03",  
    "Campos Do Jordão - 02 -z",  
    "Caçapava - 01",  
    "Caçapava - 04",  
    "Caçapava - 02",  
    "São Bento Do Sapucaí",  
    "Caçapava - 05 - z",  
    "Caçapava - 03 - z",  
    "Campos Do Jordão - 01 - z",  
    "Campos Do Jordão - 03 - z",  
    "São Luiz Do Paraitinga - z",  
    "Santo Antônio Do Pinhal - z",  
    "Sapucaí Mirim",  
    "Redenção Da Serra - z",  
    "Natividade Da Serra - z"  
  ],  
  "LM Hub_SP_Santos_Praia Grande": [  
    "02. Boqueirão",  
    "05. Ponta da Praia",  
    "14. Cubatão",  
    "01. Gonzaga",  
    "18. Porto Alemoa",  
    "07. Areia Branca",  
    "04. Embaré",  
    "03. Macuco",  
    "09. Saboó",  
    "15. Casqueiro",  
    "06. Marapé",  
    "08. Morro Santa Maria",  
    "11. Morro São Bento",  
    "17. Jardim Caraguatá",  
    "16. Vila dos Pescadores",  
    "10. Vila Nova",  
    "12. Pilões",  
    "Boqueirão",  
    "Casqueiro",  
    "Zona Noroeste - z",  
    "Vila Belmiro",  
    "Cubatão",  
    "José Menino",  
    "Aparecida",  
    "Embaré",  
    "Estuário",  
    "Ponta da Praia",  
    "Marapé",  
    "Vila Mathias",  
    "Gonzaga",  
    "Alemoa - z",  
    "Saboó - z",  
    "Jardim Caraguatá - z",  
    "Morro Santa Maria - z",  
    "Pompéia",  
    "Macuco",  
    "Vila dos Pescadores - z",  
    "Morro São Bento - z",  
    "Pilões - z",  
    "Vila Esperança - z"  
  ],  
  "LM Hub_SP_Jurubatuba": [  
    "Vila São José - 02 - z",  
    "São Luis - 02 - z",  
    "Santo Amaro - 01",  
    "Varginha - z",  
    "Interlagos",  
    "Vila Andrade - z",  
    "Vila Guarani - z",  
    "Recanto Belo",  
    "Santa Catarina - z",  
    "Morumbi - 02 - z",  
    "Parelheiros",  
    "Vila São José - 01",  
    "Americanópolis - z",  
    "Jardim Malia - 02 - z",  
    "Guarapiranga - 01",  
    "Guarapiranga - 02 - z",  
    "Jardim Malia - 01",  
    "Barragem",  
    "Morumbi - 01",  
    "Ipora - 01",  
    "Campo Belo",  
    "Moema - z",  
    "Campo Limpo - z",  
    "Parque Brasil - z",  
    "Jurubatuba - z",  
    "Saúde",  
    "São Luis - 01",  
    "Jabaquara - z",  
    "Ipora - 02 - z",  
    "Erundina - z",  
    "Cidade Ademar - z",  
    "Shangrila - z",  
    "Paraisópolis - z",  
    "Colônia",  
    "Santo Amaro - 02 - z",  
    "Marsilac",  
    "Jardim Das Fontes",  
    "Terceiro Lago",  
    "Borba Gato"  
  ],  
  "LM Hub_SP_Guaratinguetá": [  
    "26. Guaratinguetá",  
    "13. Lorena",  
    "24. Aparecida",  
    "21. Potim",  
    "07. Cruzeiro",  
    "17. Pindamonhangaba",  
    "22. Santa Luzia",  
    "14. Goiabal",  
    "16. Alto do Cardoso",  
    "18. Capituva",  
    "15. Bom Sucesso",  
    "08. Cachoeira Paulista",  
    "23. Mirante",  
    "25. Santa Edwiges",  
    "03. Lagoinha",  
    "06. Silveiras",  
    "04. Queluz",  
    "05. Lavrinhas",  
    "02. Cunha",  
    "20. Barretinho",  
    "01. Campos de Cunha",  
    "11. Piquete",  
    "10. Santa Lucrécia",  
    "12. Canas",  
    "19. Bonfim"  
  ],  
  "LM Hub_SP_Santos_PraiaGrande_02": [  
    "19. Nova Mirim",  
    "11. Vila Margarida",  
    "13. Parque das Bandeiras",  
    "08. Vila Cascatinha",  
    "14. São José do Rio Preto",  
    "12. Parque Continental",  
    "10. Cidade Náutica",  
    "06. Itanhaém",  
    "20. Praia Grande",  
    "07. Mongaguá",  
    "09. São Vicente",  
    "04. Peruíbe",  
    "05. Bopiranga",  
    "03. Guaraú",  
    "18. Guilhermina",  
    "16. Canto do Forte",  
    "17. Vila Sonia",  
    "15. Vila Caiçara",  
    "02. Itariri",  
    "Mongaguá Morro - z",  
    "São Vicente - z",  
    "Vila Margarida - z",  
    "São José do Rio Preto - z",  
    "Peruíbe - z",  
    "Vila Caiçara - z",  
    "Itanhaém Morro - z",  
    "Bopiranga Morro - z",  
    "Itanhaém Orla",  
    "Vila Sonia",  
    "Praia Grande",  
    "Cidade Náutica - z",  
    "Mongaguá Orla",  
    "Nova Mirim - z",  
    "Bopiranga Orla",  
    "Canto do Forte",  
    "Parque Continental - z",  
    "Vila Cascatinha",  
    "Parque das Bandeiras - z",  
    "Guilhermina",  
    "Itariri - z",  
    "Guaraú - z",  
    "Pedro de Toledo - z",  
    "Vila Caiçara",  
    "Vila Sonia - z"  
  ],  
  "LM Hub_SP_Mauá": [  
    "11. Parque São Rafael",  
    "07. Vila Feital",  
    "01. Vila Figueiredo",  
    "12. Jardim Oratório",  
    "17. Jardim Primavera",  
    "20. Jardim Alto Alegre",  
    "05. Santa Luzia",  
    "14. Jardim Itapark",  
    "15. Parque das Américas",  
    "04. Centro Alto",  
    "21. Jardim da Conquista",  
    "16. Recreio da Borda do Campo",  
    "09. Jardim Zaira",  
    "10. Parque das Flores",  
    "03. Ouro Fino",  
    "02. Jardim Santa Tereza",  
    "06. Jardim Luzitano",  
    "13. Jardim Sonia Maria",  
    "19. Vila Assis",  
    "08. Jardim Miranda D'Aviz",  
    "18. Parque São Vicente",  
    "Jardim Miranda D'Aviz",  
    "Santa Luzia",  
    "Parque São Rafael - 01 - z",  
    "Jardim da Conquista - z",  
    "Vila Figueiredo",  
    "Parque São Vicente",  
    "Jardim Oratório - z",  
    "Centro Alto",  
    "Jardim Alto Alegre - z",  
    "Jardim Itapark",  
    "Recreio da Borda do Campo - z",  
    "Vila Assis",  
    "Vila Feital",  
    "Jardim Santa Tereza",  
    "Parque das Américas",  
    "Parque São Rafael - 02",  
    "Ouro Fino",  
    "Jardim Zaira - z",  
    "Jardim Luzitano",  
    "Parque das Flores - z",  
    "Jardim Sonia Maria"  
  ],  
  "LM Hub_SP_São Bernardo do Campo": [  
    "14. Conceição",  
    "19. Americanópolis",  
    "13. Canhema",  
    "20. Balneário",  
    "06. Montanhão",  
    "11. Jardim Climax",  
    "10. Nova Petrópolis",  
    "08. Bairro dos Casas",  
    "17. Rudge Ramos",  
    "07. Vila São Pedro",  
    "21. Pedreira",  
    "18. Casa Grande",  
    "24. Alvarenga",  
    "16. Planalto",  
    "22. Eldorado",  
    "09. Assunção",  
    "01. Riacho Grande",  
    "15. Piraporinha",  
    "23. Inamar",  
    "03. Areião",  
    "05. Jardim Represa",  
    "12. Taboão",  
    "02. Estoril",  
    "04. Demarchi",  
    "Taboão",  
    "Jardim Climax - 01",  
    "Jardim Climax - 02",  
    "Serraria - z",  
    "Conceição - 01 - z",  
    "Canhema",  
    "Alvarenga - 03",  
    "Conceição - 04 - z",  
    "Estoril - 02",  
    "Vila São Pedro",  
    "Inamar - z",  
    "Montanhão",  
    "Eldorado - 01 - z",  
    "Bairro dos Casas - 03",  
    "Alvarenga - 02",  
    "Nova Petrópolis",  
    "Alvarenga - 04",  
    "Casa Grande",  
    "Balneário - z",  
    "Demarchi - 05",  
    "Rugde Ramos",  
    "Alvarenga - 01",  
    "Bairro dos Casas - 02",  
    "Riacho Grande - 01",  
    "Conceição - 02 - z",  
    "Pedreira - z",  
    "Conceição - 03 - z",  
    "Vila Assunção - Sto André",  
    "Areião",  
    "Piraporinha",  
    "Demarchi - 02",  
    "Demarchi - 01",  
    "Riacho Grande - 02",  
    "Eldorado - 02 - z",  
    "Vila Palmares",  
    "Assunção",  
    "Jardim Represa - 01",  
    "Demarchi - 04",  
    "Bairro dos Casas - 01",  
    "Jardim Represa - 02",  
    "Demarchi - 03",  
    "Estoril - 03",  
    "Conceição - z",  
    "Vila Capela - z",  
    "Baeta",  
    "Jardim Climax",  
    "Rudge Ramos",  
    "Parque das Garças",  
    "Jardim Miriam - z",  
    "Ferrazopolis",  
    "Riacho Grande Pós Balsa",  
    "Americanopolis - z",  
    "Eldorado - z",  
    "Terra Nova II",  
    "Demarchi",  
    "Centro SBC",  
    "Batistini",  
    "Cooperativa",  
    "Dos Casas",  
    "Las Palmas",  
    "Represa",  
    "Riacho Grande",  
    "Vila São Pedro - z",  
    "Conceição"  
  ],  
  "LM Hub_SP_Santo André": [  
    "20. Utinga",  
    "16. Aramaçan",  
    "03. Parque Boa Esperança",  
    "04. Parque São Rafael",  
    "14. Príncipe de Gales",  
    "24. Capuava",  
    "17. Jardim Santo André",  
    "09. Cerâmica",  
    "13. Barcelona",  
    "07. Promorar",  
    "15. Las Vegas",  
    "19. Parque Santa Madalena",  
    "11. Vila Bancária",  
    "10. Tamaro",  
    "21. Campestre",  
    "23. Parque das Nações",  
    "05. São Mateus",  
    "06. Imperador",  
    "22. Centro",  
    "12. Vila Ema",  
    "18. Parque Marajoara",  
    "02. Sertanistas",  
    "08. Vila Alpina",  
    "Capuava",  
    "Parque Marajoara",  
    "Parque Boa Esperança - z",  
    "Jardim Santo André",  
    "Parque das Nações",  
    "São Mateus - z",  
    "Promorar - z",  
    "Parque São Rafael - z",  
    "Vila Ema",  
    "UBS",  
    "Príncipe de Gales",  
    "Barcelona",  
    "Cerâmica",  
    "Vila Bancária - z",  
    "Tamaro - z",  
    "Vila Bancária",  
    "Parque Santa Madalena",  
    "Imperador - z",  
    "Las Vegas",  
    "Utinga",  
    "Sertanistas - z",  
    "Jardim Elba - z",  
    "Jardim Alteza",  
    "Cata Preta - z",  
    "Fazenda da Juta - z"  
  ],  
  "LM Hub_SP_Suzano_Baruel": [  
    "10. Brás Cubas",  
    "17. Suzano",  
    "13. Mogi das Cruzes",  
    "11. Cezar de Souza",  
    "12. Palmeiras de São Paulo",  
    "16. Boa Vista Paulista",  
    "08. aiaçupeba",  
    "04. Guararema",  
    "15. Jundiapeba",  
    "09. Quatinga",  
    "05. Sabaúna",  
    "01. Salesópolis",  
    "03. Biritiba Mirim",  
    "06. Biritiba-Ussu",  
    "Guararema",  
    "Jundiapeba",  
    "Suzano",  
    "Mogi das Cruzes",  
    "Brás Cubas",  
    "Palmeiras de São Paulo",  
    "Salesópolis",  
    "Cezar de Souza",  
    "Sabaúna",  
    "Boa Vista Paulista - z",  
    "Biritiba Mirim",  
    "Biritiba-Ussu",  
    "Quatinga",  
    "Aiaçupeba",  
    "Poá",  
    "Nossa Senhora do Remédio",  
    "Biritba-Ussu",  
    "Taiaçupeba",  
    "Ferraz de Vasconcelos"  
  ],  
  "LM Hub_SP_Araçatuba": [  
    "13. Vila Santo Antonio",  
    "11. Córrego Azul",  
    "14. Coroados",  
    "08. Planalto",  
    "07. Bilac",  
    "05. Vila Aeronautica",  
    "01. Buritama",  
    "09. General Salgado",  
    "06. Guararapes",  
    "15. Birigui",  
    "03. Auriflama",  
    "10. Penápolis",  
    "04. Alto Alegre",  
    "02. Avanhandava",  
    "12. Jussara",  
    "Avanhandava",  
    "Vila Santo Antonio",  
    "Vila Aeronautica",  
    "Penápolis",  
    "Buritama",  
    "Birigui",  
    "Guararapes",  
    "Coroados",  
    "General Salgado",  
    "Jussara",  
    "Auriflama",  
    "Bilac",  
    "Alto Alegre",  
    "Córrego Azul",  
    "PlanaltoRioPreto"  
  ],  
  "LM Hub_SP_Franca_Distrito_Indust": [  
    "Jardim Noemia",  
    "Ituverava",  
    "Orlândia",  
    "Jardim Portinari",  
    "Jardim Cambui",  
    "São Joaquim da Barra",  
    "Distrito Industrial",  
    "Vila Aparecida",  
    "Vila Nicacio",  
    "Jeriquara",  
    "Claraval",  
    "Jardim Panorama",  
    "Guará",  
    "Sales Oliveira",  
    "Nuporanga",  
    "Cristais Paulista",  
    "Pedregulho",  
    "Patrocínio Paulista",  
    "Jardim Aeroporto",  
    "Ipuã",  
    "Miguelópolis",  
    "Ibiraci",  
    "Ribeirão Corrente",  
    "Rifaina",  
    "São Tomás de Aquino",  
    "Restinga",  
    "São José da Bela Vista",  
    "Itirapuã",  
    "Buritizal"  
  ],  
  "LM Hub_SP_São José do Rio P": [  
    "27. Cedral",  
    "33. Jardim Canaa",  
    "31. Jardim Nazareth",  
    "23. Bady Bassitt",  
    "37. Eng. Schmitt",  
    "35. Vila São José",  
    "10. José Bonifácio",  
    "11. Novo Horizonte",  
    "24. Mirassol",  
    "20. Neves Paulista",  
    "34. São Jose do Rio Preto",  
    "14. Urupês",  
    "28. Talhado",  
    "36. Estância Jockey Clube",  
    "29. Jardim Maria Lucia",  
    "12. Sales",  
    "32. Eldorado",  
    "26. Pitirendaba",  
    "13. Irapuã",  
    "07. Macaubal",  
    "30. Parque das Aroeiras",  
    "06. Mirassolândia",  
    "03. Palestina",  
    "25. Portal",  
    "04. Nova Granada",  
    "22. Jaci",  
    "15. Ubarana",  
    "21. Bálsamo",  
    "16. Mendonça",  
    "18. Nipoã",  
    "17. Nova Aliança",  
    "Eng. Schmitt",  
    "Parque das Aroeiras",  
    "Mirassol",  
    "Jardim Nazareth",  
    "Bady Bassitt",  
    "Mirassolândia",  
    "Cedral",  
    "Palestina",  
    "Jardim Maria Lucia",  
    "Nova Granada",  
    "São Jose do Rio Preto",  
    "Novo Horizonte",  
    "José Bonifácio",  
    "Nova Aliança",  
    "Vila São José",  
    "Talhado",  
    "Mendonça",  
    "Urupês",  
    "Sales",  
    "Pitirendaba",  
    "Estância Jockey Clube",  
    "Jardim Canaa",  
    "Irapuã",  
    "Planalto",  
    "Portal",  
    "Jaci",  
    "Ubarana",  
    "Neves Paulista",  
    "Poloni",  
    "Nipoã",  
    "Bálsamo"  
  ],  
  "LM Hub_SP_São Carlos": [  
    "01. São Carlos",  
    "06. Ibaté",  
    "03. São Carlos",  
    "05. São Carlos",  
    "04. São Carlos",  
    "10. Santa Rita do Passa Quatro",  
    "09. Itirapina",  
    "07. Descalvado",  
    "12. Analândia + Corumbataí",  
    "02. Água Vermelha"  
  ],  
  "LM Hub_SP_Jaú": [  
    "03. Bariri",  
    "13. Jardim Pedro Ometto",  
    "08. Dois Corrégos",  
    "14. Jaú Centro",  
    "01. Borborema",  
    "05. Brotas",  
    "15. Pouso Alegre de Baixo",  
    "06. Barra Bonita",  
    "10. Bocaina",  
    "12. Guarapuã",  
    "04. Boracéia",  
    "09. Itapuí",  
    "11. Potunduva",  
    "07. Torrinha"  
  ],  
  "LM Hub_SP_Votuporanga": [  
    "06. Valentim",  
    "01. Rolandia",  
    "09. Nova Palmira",  
    "05. Votuporanga",  
    "11. Macaubal",  
    "14. Monte Aprazivel",  
    "15. Orindiúva",  
    "10. Tanabi",  
    "07.Sebastianlopolis",  
    "03. Américo de Campo",  
    "13. Itaiúba",  
    "02 Cardoso",  
    "04. Cosmorama",  
    "08. Magda",  
    "Votuporanga",  
    "Nova Palmira",  
    "Tanabi",  
    "Rolandia",  
    "Orindiúva",  
    "Valentim Gentil",  
    "Cosmorama",  
    "Américo de Campos",  
    "Macaubal",  
    "Cardoso",  
    "Sebastianópolis",  
    "Magda",  
    "Monte Aprazível",  
    "Itaiúba",  
    "Ibiporanga"  
  ],  
  "LM Hub_SP_Assis": [  
    "07. Cervinho",  
    "08. Assis",  
    "06. Candido Mota",  
    "02. Palmital",  
    "03. Paraguaçu Paulista",  
    "05. Tarumã",  
    "04. São José, Santa Amélia",  
    "01. Cruzalia",  
    "03.1. Borá, Paraguaçu",  
    "02.1. Palmital, Platina",  
    "01.1. Cruzália, Florínea"  
  ],  
  "LM Hub_SP_Barretos": [  
    "11. Lagoinha",  
    "08. Severína",  
    "23. Distrito Industrial",  
    "22. Vida Nova",  
    "06. Terra Roxa",  
    "21. Aeroporto",  
    "10. Guaraci",  
    "16. Guaíra",  
    "03. Bebedouro",  
    "20. Jardim California",  
    "09. Olímpia",  
    "19. Jardim Alvorada",  
    "17. Jardim Vale do Verde",  
    "05. Monte Azul Paulista",  
    "07. Cajobi",  
    "15. Miguelópolis",  
    "18. Los Angeles",  
    "24. Icém",  
    "12. Colina",  
    "01. Taiaçu",  
    "04. Viradouro",  
    "14. Laranjeiras",  
    "02. Taiúva",  
    "13. Jaborandi",  
    "Viradouro",  
    "Vida Nova",  
    "Colina",  
    "Los Angeles",  
    "Terra Roxa",  
    "Monte Azul Paulista",  
    "Jardim Vale do Verde",  
    "Guaíra",  
    "Jardim Califórnia",  
    "Severínia",  
    "Icém",  
    "Olímpia",  
    "Jardim Alvorada",  
    "Jaborandi",  
    "Bebedouro",  
    "Taiaçu",  
    "Laranjeiras",  
    "Guaraci",  
    "Cajobi",  
    "Taiúva",  
    "São José do Rio Preto",  
    "Eng. Schimitt",  
    "Lagoinha",  
    "Bady Bassit"  
  ],  
  "LM Hub_SP_Ribeirão Preto_02": [  
    "18. Planalto Verde Baixo",  
    "29. Alto Da Boa Vista",  
    "12. Sertãozinho",  
    "15. Bonfim Paulista",  
    "23. Vila Virginia",  
    "28. Jardim Canadá",  
    "13. Serrana",  
    "26. Campos Elísios",  
    "30. Centro",  
    "27. Ribeirão Verde",  
    "22. Jardim Progresso",  
    "14. Cravinhos",  
    "21. Adelino Simioni",  
    "20. Ipiranga",  
    "33. Ribeirânia",  
    "24. Vila Tiberio",  
    "25. Vila Albertina",  
    "17. Planalto Verde Alto",  
    "31. Jardim Paulista",  
    "34. Vila Abranches",  
    "19. Jardim Cristo Redentor",  
    "16. Jardim Itau Mirim",  
    "32. Distrito Indústrial",  
    "11. Dumont",  
    "10. Brodowski"  
  ],  
  "LM Hub_SP_Bauru_Centro": [  
    "12. Jardim Estoril",  
    "10. Jardim Redentor",  
    "01. Lonçóis Paulista",  
    "13. Jardim Florida",  
    "06. Pirajuí",  
    "02. Pederneiras",  
    "14. Vila Garcia",  
    "11. Jardim Shangri La",  
    "04. Duartina",  
    "03. Agudos",  
    "15. Jardim Jaragua",  
    "05. Piratininga",  
    "08. Avaí",  
    "09. Vale do Igapó",  
    "02.1 Macatuba",  
    "07. Iacanga"  
  ],  
  "LM Hub_SP_Marília": [  
    "10. Jardim Vitória",  
    "09. Garça",  
    "13. Palmital",  
    "01. Santa América",  
    "12. Dirceu",  
    "11. Parque Serra Dourada",  
    "03. Campos Novos Paulista",  
    "04. Echaporã",  
    "14. Marília",  
    "02. Quintana",  
    "07. Pompéia",  
    "08. Júlio Mesquita",  
    "06. Alvinlândia",  
    "05. Gália"  
  ],  
  "LM Hub_SP_Araraquara": [  
    "Itápolis, Tapinas",  
    "Ibitinga",  
    "Matão, Bueno de Andrada",  
    "Jardim Imperador",  
    "Taquaritinga, Jurupema",  
    "Araraquara, Centro",  
    "Portal das Araucárias",  
    "Tabatinga",  
    "Araraquara, Jd. Regina",  
    "Nova Europa, Gavião Peixoto",  
    "Jurepema, Negri",  
    "Dobrada",  
    "Américo Brasiliense",  
    "Dourado",  
    "Boa Esperança do Sul",  
    "Araraquara",  
    "Santa Lúcia",  
    "Parque das Laranjeiras",  
    "Guatapará",  
    "Rincão",  
    "Motuca",  
    "Sta. Ernestina",  
    "Gavião Peixoto",  
    "Itápolis, Guariroba",  
    "Ribeirão Bonito",  
    "Araraquara, Jardim Regina",  
    "Jurupema, Negri"  
  ],  
  "LM Hub_SP_Presidente Prudente": [  
    "HUB-A-4 Machado",  
    "HUB-A-5 Martinópolis",  
    "HUB-A-1 PP - 01",  
    "HUB-A-2 PP - 02",  
    "HUB-A-8 Rancharia",  
    "HUB-A-3 Epitácio",  
    "HUB-A-7 Pirapozinho",  
    "HUB-A-9 Venceslau",  
    "HUB-A-6 Mirante",  
    "Martinópolis",  
    "Jardim Bongiovani",  
    "Jardim Vale do Sol",  
    "Montalvão",  
    "Santo Anastácio",  
    "Mirante",  
    "Álvares Machado",  
    "Epitácio",  
    "Pirapozinho",  
    "Venceslau"  
  ],  
  "LM Hub_SP_RibeirãoPretoEstaça": [  
    "LESTE 01",  
    "SUL 03",  
    "NORTE 02",  
    "LESTE 02",  
    "OESTE 01",  
    "LESTE 03",  
    "OESTE 03",  
    "SUL 01",  
    "NORTE 04",  
    "NORTE 03",  
    "OESTE 02",  
    "SUL 02",  
    "NORTE 01"  
  ]  
}